#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-conquer
Version  : 1.3.3
Release  : 34
URL      : https://cran.r-project.org/src/contrib/conquer_1.3.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/conquer_1.3.3.tar.gz
Summary  : Convolution-Type Smoothed Quantile Regression
Group    : Development/Tools
License  : GPL-3.0
Requires: R-conquer-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-RcppArmadillo
Requires: R-matrixStats
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : R-RcppArmadillo-dev
BuildRequires : R-matrixStats
BuildRequires : buildreq-R

%description
# conquer
**Con**volution-type smoothed **qu**antil**e** **r**egression
## Description

%package lib
Summary: lib components for the R-conquer package.
Group: Libraries

%description lib
lib components for the R-conquer package.


%prep
%setup -q -n conquer
pushd ..
cp -a conquer buildavx2
popd
pushd ..
cp -a conquer buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737137961

%install
export SOURCE_DATE_EPOCH=1737137961
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/conquer/DESCRIPTION
/usr/lib64/R/library/conquer/INDEX
/usr/lib64/R/library/conquer/Meta/Rd.rds
/usr/lib64/R/library/conquer/Meta/features.rds
/usr/lib64/R/library/conquer/Meta/hsearch.rds
/usr/lib64/R/library/conquer/Meta/links.rds
/usr/lib64/R/library/conquer/Meta/nsInfo.rds
/usr/lib64/R/library/conquer/Meta/package.rds
/usr/lib64/R/library/conquer/NAMESPACE
/usr/lib64/R/library/conquer/R/conquer
/usr/lib64/R/library/conquer/R/conquer.rdb
/usr/lib64/R/library/conquer/R/conquer.rdx
/usr/lib64/R/library/conquer/help/AnIndex
/usr/lib64/R/library/conquer/help/aliases.rds
/usr/lib64/R/library/conquer/help/conquer.rdb
/usr/lib64/R/library/conquer/help/conquer.rdx
/usr/lib64/R/library/conquer/help/paths.rds
/usr/lib64/R/library/conquer/html/00Index.html
/usr/lib64/R/library/conquer/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/conquer/libs/conquer.so
/V4/usr/lib64/R/library/conquer/libs/conquer.so
/usr/lib64/R/library/conquer/libs/conquer.so
